### ISSUE TITLE
Synology FileStation API is not uptodate

### ISSUE THREAD

**Issue by Felix83000** [DominikButz/SynoClub#1]
If you take this code, change the API requests.

Here is the official Synology File Station API [Documentation](https://global.download.synology.com/download/Document/DeveloperGuide/Synology_File_Station_API_Guide.pdf)

**Comment by DominikButz** [comment]
Thank you for the hint. I currently don't maintain this repository any more but fee free to fork and update it.

**Comment by Felix83000** [comment]
My project is in swift 5 here: https://github.com/Felix83000/Eurosmart-SynologyNas-FileStation
It is nearly the same requests as SynoClub :)
